### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by datbreau** [alphamu/PinEntryEditText#31] opened 2018-04-04 14:17 UTC
I have been trying to use this library and after adding adding dependency and syncing gradle , all i get is failed to resolve: com.alimuzaffar.lib:pinentryedittext:1.3.2.

Please help

**Comment by stevyhacker** [comment] 2018-05-30 09:53
PinEntryEditText README.md should be updated, seems like a wrong version is used, 1.3.1 is correct.

**Comment by alphamu** [comment] 2018-10-13 22:42
Closing, let me know if the issue is still there

**Closed by alphamu** 2018-10-13 22:42 UTC

**Comment by saeedmashhadi** [comment] 2019-08-27 09:06
Facing the same issue in version 1.3.1. I also changed version to 1.3.3 but didn't work
